db:
  mysql:
    host: '127.0.0.1'
    port: 3306
    userName: 'root'
    password: '123456'
    dbName: 'm_cube'
    timezone: '+08:00'
    charset: 'utf8mb4'
    synchronize: false

  redis:
    host: 'localhost'
    port: 6379
    password: null
    ttl: null
    defaultCacheTTL: 60 * 60 * 24

email:
  account: '123456@qq.com'
  password: '123456'
  from: '"MCube" <123456@qq.com>'
  admin: '123456'

COS:
  # 腾讯
  Tencent:
    SecretId: '123456'
    SecretKey: '123456'
